# Generated by Django 5.0.6 on 2024-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0002_venue_pricingpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="available_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="venue",
            name="average_cost_per_person",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="venue",
            name="zip_code",
            field=models.CharField(default=44207, max_length=10),
        ),
    ]
