# Generated by Django 5.0.6 on 2024-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0003_venue_available_slots_venue_average_cost_per_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="occupancy",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
