# Generated by Django 5.0.6 on 2024-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0004_venue_occupancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="total_slots",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
