# Generated by Django 5.0.6 on 2024-06-24 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0005_venue_total_slots"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="total_slots",
        ),
    ]
