# Generated by Django 5.0.6 on 2024-06-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0008_rename_total_slots_venue_available_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="total_slots",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
