# Generated by Django 5.0.6 on 2024-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_venue_contact_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(),
        ),
    ]
