# Generated by Django 5.0.6 on 2024-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_alter_booking_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
