# Generated by Django 5.0.6 on 2024-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0014_alter_booking_booked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="venue_images/"),
        ),
    ]
