# Generated by Django 5.0.6 on 2024-07-01 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0015_venue_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="image",
        ),
    ]
