# Generated by Django 5.0.6 on 2024-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0018_booking_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(default="aaa", max_length=254),
        ),
    ]
