# Generated by Django 5.0.6 on 2024-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0019_booking_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
    ]
