# Generated by Django 5.0.6 on 2024-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0020_alter_booking_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
