# Generated by Django 5.1.4 on 2024-12-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0021_booking_checked_out"),
        ("route_manager", "0016_alter_busstop_route"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venueowner",
            old_name="business_registration_number",
            new_name="bus_registration_number",
        ),
        migrations.RenameField(
            model_name="venueowner",
            old_name="business_registration_photo",
            new_name="bus_registration_photo",
        ),
        migrations.AddField(
            model_name="venueowner",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="route_manager.route",
            ),
        ),
    ]
