# Generated by Django 5.0.4 on 2024-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="venue",
            name="contact_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
