# Generated by Django 5.0.4 on 2024-06-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_alter_pricingpackage_id_alter_venue_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingpackage",
            name="contact_email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
    ]
