# Generated by Django 5.0.4 on 2024-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0003_pricingpackage_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
    ]
