# Generated by Django 5.0.6 on 2024-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='contact_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
