# Generated by Django 5.0.6 on 2024-06-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounts_contact_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='contact_num',
        ),
    ]
