# Generated by Django 5.1.1 on 2024-12-13 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0002_remove_route_stops_alter_route_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_lon',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_lon',
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15)),
                ('driver_name', models.CharField(max_length=100)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route_manager.route')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='route_manager.route')),
            ],
        ),
    ]
