# Generated by Django 5.1.1 on 2024-12-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0004_route_end_lat_route_end_lon_route_start_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_lon',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_lon',
        ),
    ]
