# Generated by Django 5.1.1 on 2024-12-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0005_remove_route_end_lat_remove_route_end_lon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'verbose_name': 'Bus Stop', 'verbose_name_plural': 'Bus Stops'},
        ),
    ]
