# Generated by Django 5.1.4 on 2024-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0006_alter_busstop_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="route",
            name="name",
        ),
        migrations.RemoveField(
            model_name="route",
            name="starting_point",
        ),
        migrations.AddField(
            model_name="route",
            name="end_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="end_lng",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="route_data",
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="start_lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="route",
            name="start_lng",
            field=models.FloatField(default=0.0),
        ),
    ]
