# Generated by Django 5.1.4 on 2024-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0007_remove_route_destination_remove_route_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_data",
            field=models.JSONField(default=0.0),
        ),
    ]
