# Generated by Django 5.1.4 on 2024-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0008_route_name_alter_route_route_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="end_lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="end_lng",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_lng",
            field=models.FloatField(),
        ),
    ]
