# Generated by Django 5.1.4 on 2024-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0009_alter_route_end_lat_alter_route_end_lng_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="end_lat",
        ),
        migrations.RemoveField(
            model_name="route",
            name="end_lng",
        ),
        migrations.RemoveField(
            model_name="route",
            name="name",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_lat",
        ),
        migrations.RemoveField(
            model_name="route",
            name="start_lng",
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="route",
            name="route_name",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="route",
            name="starting_point",
            field=models.CharField(default="0", max_length=255),
        ),
    ]
