# Generated by Django 5.1.4 on 2024-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "route_manager",
            "0013_alter_route_destination_alter_route_route_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busstop",
            options={},
        ),
        migrations.RemoveField(
            model_name="busstop",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="busstop",
            name="lon",
        ),
        migrations.AddField(
            model_name="busstop",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="busstop",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="busstop",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
