# Generated by Django 5.1.4 on 2024-12-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0014_alter_busstop_options_remove_busstop_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="route",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stops",
                to="route_manager.route",
            ),
        ),
    ]
