# Generated by Django 5.1.4 on 2024-12-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0015_alter_busstop_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bus_stops",
                to="route_manager.route",
            ),
        ),
    ]
