# Generated by Django 5.1.4 on 2024-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_manager", "0016_alter_busstop_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
